
name: Flutter CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test_and_analyze:
    name: Test and analyze app code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app dependency (roslib)
        uses: actions/checkout@v2
        with:
          repository: PimpMyPizza/roslib
          path: ./roslib
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ./pilsbot
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Checkout flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: pub get
        run: cd pilsbot && flutter pub get
      - name: Analyze code
        run: cd pilsbot && flutter analyze
      - name: Run tests
        run: cd pilsbot && flutter test
  build_android:
    name: Build app for Android
    needs: [test_and_analyze]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout app dependency (roslib)
        uses: actions/checkout@v2
        with:
          repository: PimpMyPizza/roslib
          path: ./roslib
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ./pilsbot
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Checkout flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: pub get
        run: cd pilsbot && flutter pub get
      - run: cd pilsbot && flutter clean
        name: Clean for Android APK
      - run: cd pilsbot && flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        name: Build Android APK
      #- run: cd pilsbot && flutter clean
      #- run: cd pilsbot && flutter build appbundle
  build_ios:
    name: Build app for iOS
    needs: [test_and_analyze]
    runs-on: macos-latest
    steps:
      - name: Checkout app dependency (roslib)
        uses: actions/checkout@v2
        with:
          repository: PimpMyPizza/roslib
          path: ./roslib
      - name: Checkout app
        uses: actions/checkout@v2
        with:
          path: ./pilsbot
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - name: Checkout flutter
        uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - name: pub get
        run: cd pilsbot && flutter pub get
      - run: cd pilsbot && flutter clean
        name: Clean for iOS
      - run: cd pilsbot && flutter build ios --no-codesign
        name: Build iOS