
name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: install dependencies
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: install dependencies
      uses: subosito/flutter@v1.4.0
      with:
        args: pub get

    - name: run tests
      uses: subosito/flutter@v1.4.0
      with:
        args: test

    - name: build apk
      uses: subosito/flutter@v1.4.0
      with:
        args: build apk --release --target-platform android-arm,android-arm64,android-x64 --split-per-abi
